name: CI Docker - TP DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Tester la construction de l'image Docker
      # Assure-toi que ton fichier Dockerfile est bien présent à la racine de ton dépôt !
      run: docker build -t test-image .
